#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get -y install haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 77585-web-01 54.160.126.209:80 check
   server 77585-web-02 54.208.232.134:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
