#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
s="Best School"
count=0
while [[ "$count" -lt 10 ]]
do
	if [[ $count -eq 8 ]]
	then
		echo "Hi"
		count=$count+1
		continue
	fi
	echo "$s"
	count=$count+1
done
