#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
s="Best School"
count=1
while [[ "$count" -lt 11 ]]
do
	if [[ $count -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $count -eq 8 ]]
	then
		echo "good luck"
	else
		echo "$s"
	fi
	count=$count+1
done
