#!/usr/bin/env bash
# configures a ufw firewall

apt-get -y update
apt-get -y install ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outcoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
